# HTTP Server

server:
  port: 8089   # HTTP (Tomcat) port

spring:
  profiles:
    active: local


#日志采用debug模式
error: true
#debug: true

---
#本地环境
spring:
  profiles: local

  #thymeleaf 配置
  thymeleaf:
    cache: false
    #模版文件存放的位置
    prefix: classpath:/templates/
    #uffix that gets appended to view names when building a URL.
    suffix: .html

  datasource:
    primary:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/bootdb?useUnicode=true&amp;characterEncoding=utf-8&amp;allowMultiQueries=true
      username: root
      password: root


    secondary:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/bootdb2?useUnicode=true&amp;characterEncoding=utf-8&amp;allowMultiQueries=true
      username: root
      password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# REDIS (RedisProperties)
# Redis数据库索引（默认为0）
  redis:
    database: 0
    host: localhost
    port: 6379
    password: xue$Xin+2@!3
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
    # 连接超时时间（毫秒）
    timeout: 0

  session:
    store-type: redis


  mail:
    protocol: smtp
    host: smtp.263.net
    port: 25
    username: zhangxiaolong@weimingedu.com
    password: wmjy+2696
    default-encoding: UTF-8


#  //以谁来发送邮件
mail:
  fromMail:
    addr: zhangxiaolong@weimingedu.com






logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE

---
#开发环境
spring:
  profiles: dev

jdbc:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost:3306/bootdb?useUnicode=true&amp;characterEncoding=utf-8&amp;allowMultiQueries=true
  username: root
  password: root1